//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceAssistantTest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoiceAssistantTest.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity string is malformed - not a valid activity..
        /// </summary>
        public static string ACTIVITY_STRING_MALFORMED {
            get {
                return ResourceManager.GetString("ACTIVITY_STRING_MALFORMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity does not have &quot;type&quot; field set. Please set the &quot;type&quot; field..
        /// </summary>
        public static string ACTIVITY_TYPE_NOT_SET {
            get {
                return ResourceManager.GetString("ACTIVITY_TYPE_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All 3 inputs - text utterance, activity and WAVFile are present. .
        /// </summary>
        public static string ALL_PRESENT {
            get {
                return ResourceManager.GetString("ALL_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the test files are marked to skip..
        /// </summary>
        public static string ALL_TESTFILES_SKIPPED {
            get {
                return ResourceManager.GetString("ALL_TESTFILES_SKIPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input turn is ambiguous. Not a valid combination..
        /// </summary>
        public static string AMBIGUOUS_TURN_INPUT {
            get {
                return ResourceManager.GetString("AMBIGUOUS_TURN_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to establish bot connection..
        /// </summary>
        public static string AUTHENTICATION_ERROR {
            get {
                return ResourceManager.GetString("AUTHENTICATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Region is invalid. Needed to make bot connections..
        /// </summary>
        public static string AZURE_REGION_INVALID {
            get {
                return ResourceManager.GetString("AZURE_REGION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Region is missing. Needed to make bot connections..
        /// </summary>
        public static string AZURE_REGION_MISSING {
            get {
                return ResourceManager.GetString("AZURE_REGION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This turn should not have any input, as it is supposed to check bot greeting..
        /// </summary>
        public static string BOT_GREETING_MISSING {
            get {
                return ResourceManager.GetString("BOT_GREETING_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file is not specified. Please pass a valid configuration file as an argument..
        /// </summary>
        public static string CONFIG_FILE_MISSING {
            get {
                return ResourceManager.GetString("CONFIG_FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Command App Id is invalid..
        /// </summary>
        public static string CUSTOM_COMMANDS_APP_ID_INVALID {
            get {
                return ResourceManager.GetString("CUSTOM_COMMANDS_APP_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Speech Recognition Endpoint Id is invalid..
        /// </summary>
        public static string CUSTOM_SR_ENDPOINT_ID_INVALID {
            get {
                return ResourceManager.GetString("CUSTOM_SR_ENDPOINT_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Voice Deployment Id is invalid..
        /// </summary>
        public static string CUSTOM_VOICE_DEPLOYMENT_ID_INVALID {
            get {
                return ResourceManager.GetString("CUSTOM_VOICE_DEPLOYMENT_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog ID&apos;s in Test File are not unique..
        /// </summary>
        public static string DUPLICATE_DIALOGID {
            get {
                return ResourceManager.GetString("DUPLICATE_DIALOGID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Output Folder..
        /// </summary>
        public static string FAILED_CREATING_OUPUT_FOLDER {
            get {
                return ResourceManager.GetString("FAILED_CREATING_OUPUT_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with this name and path does not exist..
        /// </summary>
        public static string FILE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("FILE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test file names may include relative path, not full paths..
        /// </summary>
        public static string FILENAME_PATH_NOT_RELATIVE {
            get {
                return ResourceManager.GetString("FILENAME_PATH_NOT_RELATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not found. .
        /// </summary>
        public static string FOLDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("FOLDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Input test files were specified..
        /// </summary>
        public static string INPUT_FILE_MISSING {
            get {
                return ResourceManager.GetString("INPUT_FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputType must be either Audio or Utterance..
        /// </summary>
        public static string INPUTTYPE_INCORRECT {
            get {
                return ResourceManager.GetString("INPUTTYPE_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TurnID sequence is invalid..
        /// </summary>
        public static string INVALID_TURNID_SEQUENCE {
            get {
                return ResourceManager.GetString("INVALID_TURNID_SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword Recognition Model File not found. .
        /// </summary>
        public static string KEYWORD_RECOGNITION_MODEL_NOT_FOUND {
            get {
                return ResourceManager.GetString("KEYWORD_RECOGNITION_MODEL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Latency string is malformed - not a valid expected latency..
        /// </summary>
        public static string LATENCY_STRING_MALFORMED {
            get {
                return ResourceManager.GetString("LATENCY_STRING_MALFORMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When ExpectedResponses is missing or an empty array (&quot;bootstraping mode&quot;), you should not specify ExpectedUserPerceivedLatency..
        /// </summary>
        public static string LATENCY_STRING_PRESENT {
            get {
                return ResourceManager.GetString("LATENCY_STRING_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep duration cannot be a negative number..
        /// </summary>
        public static string NEGATIVE_SLEEP_DURATION {
            get {
                return ResourceManager.GetString("NEGATIVE_SLEEP_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn ID must be a non-negative integer..
        /// </summary>
        public static string NEGATIVE_TURNID {
            get {
                return ResourceManager.GetString("NEGATIVE_TURNID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder does not have write permissions for the user running the code..
        /// </summary>
        public static string NO_WRITE_ACCESS_FOLDER {
            get {
                return ResourceManager.GetString("NO_WRITE_ACCESS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All input fields are empty..
        /// </summary>
        public static string NONE_PRESENT {
            get {
                return ResourceManager.GetString("NONE_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR operator occurrence is inconsistent among corresponding expected text, speak, and ExpectedTTSAudioDuration..
        /// </summary>
        public static string OR_OCCURRENCE_INCONSISTENT {
            get {
                return ResourceManager.GetString("OR_OCCURRENCE_INCONSISTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Recognition Language is invalid..
        /// </summary>
        public static string SR_LANGUAGE_INVALID {
            get {
                return ResourceManager.GetString("SR_LANGUAGE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Key is invalid (expecting a GUID)..
        /// </summary>
        public static string SUBSCRIPTION_KEY_INVALID {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_KEY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Key is missing. Needed to make bot connections..
        /// </summary>
        public static string SUBSCRIPTION_KEY_MISSING {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_KEY_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A negative number is not a valid value for Timeout..
        /// </summary>
        public static string TIMEOUT_INVALID {
            get {
                return ResourceManager.GetString("TIMEOUT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of ExpectedTTSAudioDurations does not match the size of ExpectedResponses..
        /// </summary>
        public static string TTS_AUDIO_DURATION_INVALID {
            get {
                return ResourceManager.GetString("TTS_AUDIO_DURATION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A negative number is not a valid value for TTSAudioDurationMargin..
        /// </summary>
        public static string TTS_AUDIO_DURATION_MARGIN_INVALID {
            get {
                return ResourceManager.GetString("TTS_AUDIO_DURATION_MARGIN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When ExpectedResponses is missing or an empty array (&quot;bootstraping mode&quot;), you should not specify ExpectedTTSAudioDurations. Otherwise, the size of ExpectedResponses and ExpectedTTSAudioDurations should be same..
        /// </summary>
        public static string TTS_AUDIO_DURATION_PRESENT {
            get {
                return ResourceManager.GetString("TTS_AUDIO_DURATION_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpectedTTSAudioDurations is not valid. Zero and negative values other than -1 are not valid..
        /// </summary>
        public static string TTS_AUDIO_DURATION_VALUES_INVALID {
            get {
                return ResourceManager.GetString("TTS_AUDIO_DURATION_VALUES_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Utterance and Activity field present. .
        /// </summary>
        public static string UTTERANCE_ACTIVITY_PRESENT {
            get {
                return ResourceManager.GetString("UTTERANCE_ACTIVITY_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both WAV fIle and Activity field present. .
        /// </summary>
        public static string WAV_FILE_ACTIVITY_PRESENT {
            get {
                return ResourceManager.GetString("WAV_FILE_ACTIVITY_PRESENT", resourceCulture);
            }
        }
    }
}
