// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Handle Exception based on implementation requirements", Scope = "member", Target = "~M:UWPVoiceAssistantSample.AgentAudioProducer.PerformAudioSetup~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Handle Exception based on implementation requirements", Scope = "member", Target = "~M:UWPVoiceAssistantSample.AppSharedState.GetSessionAsync~System.Threading.Tasks.Task{Windows.ApplicationModel.ConversationalAgent.ConversationalAgentSession}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Handle Exception based on implementation requirements", Scope = "member", Target = "~M:UWPVoiceAssistantSample.AppSharedState.Initialize")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Arguments must be defined but cannot be discarded", Scope = "member", Target = "~M:UWPVoiceAssistantSample.MainPage.StopPlayback_Clicked(System.Object,Windows.UI.Xaml.RoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CA1801:Remove unused parameter", Justification = "Arguments must be defined but cannot be discarded", Scope = "member", Target = "~M:UWPVoiceAssistantSample.MainPage.StopPlayback_Clicked(System.Object,Windows.UI.Xaml.RoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Exception message not to be localized", Scope = "member", Target = "~M:UWPVoiceAssistantSample.KeywordRegistration.SetModelDataIfNeededAsync(Windows.ApplicationModel.ConversationalAgent.ActivationSignalDetectionConfiguration,UWPVoiceAssistantSample.KeywordRegistration)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Exception message not to be localized", Scope = "member", Target = "~M:UWPVoiceAssistantSample.MVARegistrationHelpers.UnlockLimitedAccessFeature")]
